#!/bin/bash
git add .;
git commit -m "preparing branch point before compilation"

sibilant src/*.sibilant -o lib/
compile_state=$?

git add .


if [compile-state -ne 0]
then echo "failed";
     git stash;

else git commit -m "successfully compiled";
     git push my-fork master;
     echo "success"
fi
